[project]
name = "graiax-text2img-playwright"
version = "0.1.0b1"
description = "基于 Playwright 的适用于 Graia 的文转图工具"
authors = [
    {name = "Redlnn", email = "w731347477@gmail.com"},
]
dependencies = [
    "graiax-playwright>=0.1.2",
    "jinja2>=3.1.2",
    "launart>=0.6.1",
    "markdown-it-py[linkify,plugins]>=2.1.0",
    "pygments>=2.13.0",
    "typing-extensions>=4.3.0",
]
keywords = ["graia", "graiax", "text2img", "playwright", "jinja2"]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
repository = "https://github.com/GraiaCommunity/graiax-text2img-playwright"

[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "flake8>=5.0.4",
    "black>=22.8.0",
    "isort>=5.10.1",
]

[tool.pdm.build]
includes = ["src/graiax"]

[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
