name: Python package
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      release:
        description: Make Release
        required: true
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PDM
        uses: pdm-project/setup-pdm@main

      - name: Build Package
        run: |
          pdm build

      - name: Publish to PyPI
        if: ${{ github.event_name == 'push' }} || ${{ github.event.inputs.release == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true
